### PR TITLE
Edit for clarity and grammar

### PR DESCRIPTION
**Pull request by adrianhacker-pdx**
Hello,  I have applied to work on this bounty through Gitcon.  I completed revisions of the docs in "ecosystem".  If you are pleased with the results, please approve me to work on the bounty and I will finish the rest of the work.

### CODE REVIEW

**Comment by adrianhacker-pdx** [comment]
Ecosystem and Learn folders have been completed so far.  Continuing on to the last folder, workshop-and-tutorial.  Also, I am uncertain why the build is erroring for the Introduction.md file.  I have not made any changes to it.

**Comment by adrianhacker-pdx** [comment]
All edits are complete in the Tutorial, Ecosystem, and Learn folders per the bounty.  Conflicts keep arising in workshop-and-tutorial/dapps-reward.md  and I don't know why.  Someone working on that file?

**Comment by SotaWatanabe** [comment]
Thank you for your quick work. let me solve some conflicts :)

**Comment by SotaWatanabe** [comment]
It seems that one of our devs worked on it. I will solve the conflict soon!

**Pull request closed without merging**
